server:
  port: 8081

spring:
  application:
    name: high-roller-network-reactive

  r2dbc:
    #url: r2dbc:h2:file:///./highrollerdb
    url: r2dbc:h2:mem:///highrollerdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
