server:
  port: 8080

spring:
  application:
    name: highrollernetwork

  datasource:
    url: jdbc:h2:mem:highrollerdb
    ##url: jdbc:h2:mem:highrollerdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
